"""core 模块."""

from .client import Client
from .endpoint import (
    CgiEndpointMeta,
    CgiRequestData,
    EndpointMeta,
    HttpEndpointMeta,
    HttpRequestData,
    cgi_endpoint,
    get_endpoint_meta,
    http_endpoint,
)
from .engine import RequestCall, RequestEngine, RequestScope
from .exceptions import (
    ApiDataError,
    ApiException,
    BaseApiException,
    CgiApiException,
    CredentialExpiredError,
    CredentialInvalidError,
    CredentialRefreshError,
    GlobalApiError,
    HTTPError,
    LoginAccountRestrictedError,
    LoginAuthExpiredError,
    LoginDeviceLimitError,
    LoginError,
    LoginRateLimitError,
    NetworkError,
    RatelimitedError,
    TimeoutNetworkError,
)
from .request import BaseRequest, CgiRequest, HttpRequest, ItemPaginatedCgiRequest, PaginatedCgiRequest
from .response import RawPayload
from .transport import RawStream, StreamingTransport
from .versioning import DEFAULT_VERSION_POLICY, Platform, VersionPolicy, VersionProfile

__all__ = [
    "DEFAULT_VERSION_POLICY",
    "ApiDataError",
    "ApiException",
    "BaseApiException",
    "BaseRequest",
    "CgiApiException",
    "CgiEndpointMeta",
    "CgiRequest",
    "CgiRequestData",
    "Client",
    "CredentialExpiredError",
    "CredentialInvalidError",
    "CredentialRefreshError",
    "EndpointMeta",
    "GlobalApiError",
    "HTTPError",
    "HttpEndpointMeta",
    "HttpRequest",
    "HttpRequestData",
    "ItemPaginatedCgiRequest",
    "LoginAccountRestrictedError",
    "LoginAuthExpiredError",
    "LoginDeviceLimitError",
    "LoginError",
    "LoginRateLimitError",
    "NetworkError",
    "PaginatedCgiRequest",
    "Platform",
    "RatelimitedError",
    "RawPayload",
    "RawStream",
    "RequestCall",
    "RequestEngine",
    "RequestScope",
    "StreamingTransport",
    "TimeoutNetworkError",
    "VersionPolicy",
    "VersionProfile",
    "cgi_endpoint",
    "get_endpoint_meta",
    "http_endpoint",
]
